version: 1.0
compose-app: docker compose
# env-file: .env
defaults:
  group: dev
  project-name: retsu
groups:
  dev:
    compose-path:
      - containers/compose.yaml
    # env-file: .env
    services:
      default: valkey #,celery
      available:
        - name: valkey
        # - name: celery
