[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "retsu"
version = "0.4.0"  # semantic-release
description = "A lightweight resource and concurrency control layer for Python background jobs"
readme = "README.md"
authors = [
  {name = "Ivan Ogasawara", email = "ivan.ogasawara@gmail.com"},
]
license = "BSD-3-Clause"
requires-python = ">=3.10,<4"
dependencies = [
  "atpublic>=4.0",
  "redis>=5",
  "typing-extensions>=4.12.0",
]

[project.optional-dependencies]
celery = [
  "celery>=5",
]
django = [
  "django>=3",
]
ray = [
  "ray>=2",
]

[project.scripts]
retsu = "retsu.cli.main:main"

[tool.poetry]
packages = [
  {include = "retsu", from="src"},
]
exclude = [
  ".git/*",
  ".env*",
]
include = ["src/retsu/py.typed"]


[tool.poetry.group.dev.dependencies]
pytest = ">=7.3.2"
pytest-cov = ">=4.1.0"
coverage = ">=7.2.7"
celery = ">=5"
pre-commit = ">=3.3.2"
ruff = ">=0.2.0"
mypy = ">=1.5.0"
bandit = ">=1.7.5"
vulture = ">=2.7"
mccabe = ">=0.6.1"
ipython = "<8"
ipykernel = ">=6.0.0"
Jinja2 = ">=3.1.2"
quarto-cli = ">=1.9.37"
makim = ">=1.29.0"
flask = ">=3"
containers-sugar = ">=1.19.2"
compose-go = ">=2.40.3"
django = ">=3"
django-stubs = ">=3"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
markers = [
    "no_services: test does not require Redis or Celery services",
    "redis: test requires Redis or Valkey",
]

[tool.bandit]
exclude_dirs = ["tests"]
targets = "./"

[tool.vulture]
exclude = ["tests"]
ignore_decorators = []
ignore_names = []
make_whitelist = true
min_confidence = 80
paths = ["./"]
sort_by_size = true
verbose = false

[tool.ruff]
line-length = 79
force-exclude = true
src = ["./"]
exclude = [
  'docs',
]
fix = true

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "D",   # pydocstyle
  "YTT", # flake8-2020
  "RUF", # Ruff-specific rules
  "I001",  # isort
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
# Use a single line between direct and from import
lines-between-types = 1

[tool.mypy]
python_version = "3.10"
check_untyped_defs = true
strict = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ["examples/", "scripts/"]
