services:
  valkey:
    image: valkey/valkey:7.2.5-alpine
    hostname: valkey
    command: ["valkey-server", "--save", "", "--appendonly", "no"]
    ports:
      - "${RETSU_REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 2s
      timeout: 1s
      retries: 30

  # celery:
  #   hostname: celery
  #   build:
  #     context: ..
  #     dockerfile: containers/celery/Dockerfile
  #   command: celery --app=config worker --loglevel=INFO  --concurrency=4
  #   depends_on:
  #     - valkey
