version: '3.9'

services:
  valkey:
    image: valkey/valkey:7.2.5-alpine
    hostname: valkey
    container_name: valkey

  celery:
    hostname: celery
    container_name: celery
    build:
      context: ..
      dockerfile: containers/celery/Dockerfile
    command: celery --app=config worker --loglevel=INFO  --concurrency=4
    depends_on:
      - valkey
