name: retsu
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python >=3.8.1,<4
  - pip
  - poetry
  - nodejs # used by semantic-release
  - pip:
    # fix issues with distlib
    - paginate
